
# tap repositories and their packages

tap homebrew/core
brew bat
brew btop
brew docker-completion
brew eza
brew fzf
brew gh
brew neovim
brew thefuck
brew zoxide

# Main file
main ./Brewfile.$PLATFORM
