# --- Appearance Configurations ---

## Catppuccin
set -g @catppuccin_flavor 'macchiato' # or frappe, macchiato, mocha
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_status 'no'
set -g @catppuccin_window_default_text '#W'
set -g @catppuccin_window_current_fill 'number'
set -g @catppuccin_window_current_text '#W'
set -g @catppuccin_window_current_color '#{E:@thm_surface_2}'
set -g @catppuccin_date_time_text ' %b %e %H:%M'
set -g @catppuccin_status_module_text_bg '#{E:@thm_mantle}'
set -g @catppuccin_status_background "default"

# set left and right status bar
set -g allow-rename off
set -g status-position bottom
set -g status-interval 5
set -g status-left-length 100
set -g status-right-length 100
set -g status-left '#{E:@catppuccin_status_session} '
set -gF status-right '#{E:@catppuccin_status_primary_ip}'
if 'test -r /sys/class/power_supply/BAT*' {
  set -agF status-right '#{E:@catppuccin_status_battery}'
}
set -ag status-right '#{E:@catppuccin_status_date_time}'