# --- Plugins ---

## Basic
set -g @plugin 'tmux-plugins/tmux-yank'

## Theme / Style
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'alexwforsythe/tmux-which-key'  # prefix + space

## Tooling
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'omerxx/tmux-floax'
