# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$docker_context\
$conda\
$custom\
$sudo\
$cmd_duration\
$line_break\ 
$status\
$container\
$character"""

right_format = """$time"""

[character]
success_symbol = '[❯](bold #9C6CE7)'
error_symbol ='[❯](bold #BD4E67)'

[conda]
symbol = " "
format = '[$symbol$environment]($style) '
style = 'dimmed green'

[directory]
read_only = ""
truncation_length = 2
# truncate_to_repo = false
style = 'italic #67B7EE'
read_only_style = '#FFC600'
truncation_symbol = '.../'

[docker_context]
symbol = " "

[git_branch]
symbol = ""
format = '[$symbol$branch(:$remote_branch)]($style)'
style = 'bold #7D7D7D'

[git_status]
format = '[$modified$conflicted$stashed$staged$renamed]($style) $deleted$untracked$ahead_behind'
ahead = '[⇡${count} ](#9AEDFF)'
diverged = '[⇡${ahead_count }⇣${behind_count}](purple)'
behind = '[⇣${count} ](#FFC600)'
conflicted = '!='
untracked = '[](bold #FFC600)'
deleted = '[](bold #DD0000)'
modified = '*'
renamed = '»'
staged = '+'
stashed = '\\$'
style = 'bold #7D7D7D'
up_to_date = ''

# [nodejs]
# format = '[$symbol($version )]($style)'
# symbol = " "
# version_format = 'v${major}.${minor}'

[package]
disable = true

# [time]
# disabled = false
# style = 'bold #8E8E8E'
