#!/bin/sh
command cd ~/GitHub/Univ./Codes/Algo/${1::2}\_work && clang -Wall -fsanitize=undefined -fno-omit-frame-pointer -g $1\_22266013.c -o ../out/$1\_22266013 && ASAN_OPTIONS=detect_leaks=1 ../out/$1\_22266013 < in$1-$2.txt | diff -y ~/GitHub/Univ./Codes/Algo/${1::2}_work/out$1-$2.txt -
