#!/bin/sh

command cd ~/GitHub/Univ./Codes/Algo/finalreport/src/ && clang -Wall -fsanitize=undefined -fno-omit-frame-pointer -g script/$1.c -o out/$1 && ASAN_OPTIONS=detect_leaks=1 out/$1 < res/testcase/in_$2.txt

