# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 5000

# Inserts a blank line between shell prompts
add_newline = true

format = """
$directory\
$git_branch$git_status \
$docker_context\
$custom\
$sudo\
$line_break\
$conda\
$status\
$container\
$character\
"""

right_format = """$cmd_duration$job$time"""

[character]
success_symbol = '[❯](bold #948ae3)'
error_symbol ='[❯](bold #fc618d)'

[conda]
symbol = ""
format = '[$symbol$environment]($style) '
style = '#808080'

[directory]
read_only = ""
truncation_length = 2
# truncate_to_repo = false
style = 'italic #5ad4e6'
read_only_style = '#FFC600'
truncation_symbol = '.../'

[docker_context]
symbol = " "

[git_branch]
symbol = ""
format = '[$symbol$branch(:$remote_branch)]($style)'
style = 'bold #7D7D7D'

[git_status]
format = '[$modified$conflicted$stashed$staged$renamed]($style) $deleted$untracked$ahead_behind'
ahead = '[⇡${count} ](#9AEDFF)'
diverged = '[⇡${ahead_count }⇣${behind_count}](purple)'
behind = '[⇣${count} ](#FFC600)'
conflicted = '!='
untracked = '[](bold #FFC600)'
deleted = '[](bold #DD0000)'
modified = '*'
renamed = '»'
staged = '+'
stashed = '\\$'
style = 'bold #7D7D7D'
up_to_date = ''

# [nodejs]
# format = '[$symbol($version )]($style)'
# symbol = " "
# version_format = 'v${major}.${minor}'

[package]
disable = true

# [time]
# disabled = false
# style = 'bold #8E8E8E'
